export const SET_CURRENT_WEATHER = "SET_CURRENT_WEATHER";
export const SET_FORECAST_WEATHER = "SET_FORECAST_WEATHER";

export const FACEBOOK_LOGIN_SUCCESS = "FACEBOOK_LOGIN_SUCCESS";
export const FACEBOOK_LOGIN_ERROR = "FACEBOOK_LOGIN_ERROR";
